### ISSUE TITLE
Сделать скрипт, который считает длину файлов

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/podcast.11ty#1]
В package.json нужно добавить скрипт `length`, который делает следующее:

1. Проходит по списку файлов `mp3/n.mp3`, где `n` число от 1 и дальше
2. Выполняет команду `wc -c n.mp3` и получает вывод `xxx n.mp3`
3. Извлекает подстроку `xxx` из вывода и пишет её в файл `src/episodes/n.md`

```yml
audio:
  duration: 00:00:00
  length: xxx
```

Сам скрипт это `src/length.js`.
